# This is the main configuration file for Wrench.
# You must change all channel IDs, user IDs, etc. to your liking.
# Below is an example of what the file should look like.

bot:
  # Name of the bot
  name: "Wrench"

  prefix:
    # Allow mention as prefix
    mention: false

    # Prefix for commands
    commands: "]"

  # Language file used
  language: "en"

  # The common reply delete delay (seconds)
  # Used mostly in commands
  delete-delay: 3

  # List of owners (user ID)
  owners:
  - "272466470510788608"

guild:
  id: "684495087534866437"

  roles:
    admin: "898010760750440469"

# Colors used throughout messages (HEX)
colors:
  # Primary color
  primary: "#4DABF7"

  # Secondary color
  secondary: "#4F545C"

  # Color for dangerous actions
  destructive: "#ED4448"

  # Color for successful actions
  success: "#3EA55E"

# List of file types for nicknamer
file-types:
- AAC
- AVI
- BIN
- BMP
- CSS
- CSV
- DOC
- DOCX
- EPUB
- GZ
- GIF
- HTML
- ICO
- JAR
- JPG
- JSON
- MIDI
- MP3
- MP4
- MPKG
- OGG
- OTF
- PNG
- PDF
- PHP
- RAR
- SH
- SVG
- SWF
- TAR
- TIFF
- TS
- TTF
- TXT
- WAV
- WEBM
- WEBP
- WOFF2
- XML
- ZIP
- 7Z
- CIA
- 3DSX
- ROM

# Don't change!
version: 1.0.0
